### ISSUE TITLE
Make Reference<T>.FromArray() take a span<T> isntead T[]

### ISSUE THREAD

**Issue by Shpendicus** [dotnet/dotNext#129]
Title.

Cause i heavily work with spans and this would be awesome to have, i know i can make a span to a pointer but its abit more unnessecary ugly code, so its cleaner that way, unless you have a hard reason to stick to the array params.

**Comment by sakno** [comment]
@Shpendicus , thanks for suggestion. However, this is not possible, because [Reference&lt;TValue&gt;](https://dotnet.github.io/dotNext/api/DotNext.Runtime.Reference-1.html) is a **struct**, not **ref struct**. It means that an instance of `Reference` may have larger lifetime than underlying `Span`:
```csharp
static Reference<int> GetRef()
{
    Span<int> span = stackalloc int[10];
    return Reference.FromSpan(span);
}
```

If you sure that the underlying `Span` lifetime is fully controlled and safe, use `Reference.FromPointer` instead because it requires **unsafe** modifier which clearly indicates potentially dangerous part of your code.

**Comment by Shpendicus** [comment]
Yes i sometimes forget that span<T> can point to legit any contigous block of memory, wherever it was allocated and all that, so also unmanged memory. Understood, thank you!

**Comment by CodingMadness** [comment]
Hi, another Question to this, when ``Reference.FromPointer(ptr)`` is being used, does your struct handle also the "GC-ref-tracking " story, like does it update or will the pointer stayy the same and gets invalid once  GC move stuff around=?
