### ISSUE TITLE
Adding TryGetValue extension method to IReadOnlyDictionary

### ISSUE THREAD

**Issue by AlexGirardDev** [dotnet/dotNext#190]
So i noticed that there isn't an extension method for TryGetValue on specfically IReadOnlyDictionary

there is a static method on the dictionary class [here](https://github.com/dotnet/dotNext/blob/5af87551d83bf8b04ae6cae87f0b8f42d086f6fb/src/DotNext/Collections/Generic/Dictionary.cs#L333-L342)  that exsists but a extension would be much nicer syntax.

Would you all be open to me submititng a PR to add this extension method?

**Comment by sakno** [comment]
Could you propose exact API?

**Comment by AlexGirardDev** [comment]
Just adding the `this` keyword

**Comment by sakno** [comment]
It can be problematic because of ambiguity with another extension method `TryGetValue` in the same class. The second method has **this** modifier but for `IDictionary<K, V>` type. Unfortunately, `IDictionary<,>` doesn't derive from `IReadOnlyDictionary`. Additing **this** for another overload causes compilation error for the following code:
```csharp
Dictionary<int, string> dict = new();
dict.TryGetValue(42); // which one TryGetValue to call?
```
